//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Appointment {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Appointment() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Clinica.Common.Resources.Appointment", typeof(Appointment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        internal static string schedule_now {
            get {
                return ResourceManager.GetString("schedule_now", resourceCulture);
            }
        }
        
        internal static string welcome_title {
            get {
                return ResourceManager.GetString("welcome_title", resourceCulture);
            }
        }
        
        internal static string welcome_message_1 {
            get {
                return ResourceManager.GetString("welcome_message_1", resourceCulture);
            }
        }
        
        internal static string welcome_message_2 {
            get {
                return ResourceManager.GetString("welcome_message_2", resourceCulture);
            }
        }
        
        internal static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        internal static string modal_delete_message {
            get {
                return ResourceManager.GetString("modal_delete_message", resourceCulture);
            }
        }
        
        internal static string modal_delete_title {
            get {
                return ResourceManager.GetString("modal_delete_title", resourceCulture);
            }
        }
    }
}
