//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forms {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Clinica.Common.Resources.Forms", typeof(Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string enter_name {
            get {
                return ResourceManager.GetString("enter_name", resourceCulture);
            }
        }
        
        public static string enter_email {
            get {
                return ResourceManager.GetString("enter_email", resourceCulture);
            }
        }
        
        public static string enter_subject {
            get {
                return ResourceManager.GetString("enter_subject", resourceCulture);
            }
        }
        
        public static string enter_message {
            get {
                return ResourceManager.GetString("enter_message", resourceCulture);
            }
        }
        
        public static string name_required {
            get {
                return ResourceManager.GetString("name_required", resourceCulture);
            }
        }
        
        public static string subject_required {
            get {
                return ResourceManager.GetString("subject_required", resourceCulture);
            }
        }
        
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        public static string enter_phone_number {
            get {
                return ResourceManager.GetString("enter_phone_number", resourceCulture);
            }
        }
        
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        public static string email_validation_required {
            get {
                return ResourceManager.GetString("email_validation_required", resourceCulture);
            }
        }
        
        public static string email_validation_invalid {
            get {
                return ResourceManager.GetString("email_validation_invalid", resourceCulture);
            }
        }
        
        public static string password_validation_required {
            get {
                return ResourceManager.GetString("password_validation_required", resourceCulture);
            }
        }
        
        public static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        public static string forgot_password_question {
            get {
                return ResourceManager.GetString("forgot_password_question", resourceCulture);
            }
        }
        
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        public static string value_validation_normalization_error {
            get {
                return ResourceManager.GetString("value_validation_normalization_error", resourceCulture);
            }
        }
        
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
    }
}
