//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Material {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Material() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clinica.Common.Resources.Material", typeof(Material).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string data_table_actions_header {
            get {
                return ResourceManager.GetString("data_table_actions_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delete action was not performed successfully. Please try again later..
        /// </summary>
        internal static string data_table_delete_generic_error_message {
            get {
                return ResourceManager.GetString("data_table_delete_generic_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string data_table_delete_modal_cancel_button {
            get {
                return ResourceManager.GetString("data_table_delete_modal_cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string data_table_delete_modal_confirm_button {
            get {
                return ResourceManager.GetString("data_table_delete_modal_confirm_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item? You cannot undo this action..
        /// </summary>
        internal static string data_table_delete_modal_message {
            get {
                return ResourceManager.GetString("data_table_delete_modal_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm action.
        /// </summary>
        internal static string data_table_delete_modal_title {
            get {
                return ResourceManager.GetString("data_table_delete_modal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully deleted!.
        /// </summary>
        internal static string data_table_delete_successful {
            get {
                return ResourceManager.GetString("data_table_delete_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        internal static string mat_table_first_page_label {
            get {
                return ResourceManager.GetString("mat_table_first_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        internal static string mat_table_items_per_page_label {
            get {
                return ResourceManager.GetString("mat_table_items_per_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        internal static string mat_table_last_page_label {
            get {
                return ResourceManager.GetString("mat_table_last_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string mat_table_next_page_label {
            get {
                return ResourceManager.GetString("mat_table_next_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string mat_table_previous_page_label {
            get {
                return ResourceManager.GetString("mat_table_previous_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 of {{length}}.
        /// </summary>
        internal static string mat_table_range_page_label_1 {
            get {
                return ResourceManager.GetString("mat_table_range_page_label_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{startIndex}} - {{endIndex}} of {{length}}.
        /// </summary>
        internal static string mat_table_range_page_label_2 {
            get {
                return ResourceManager.GetString("mat_table_range_page_label_2", resourceCulture);
            }
        }
    }
}
