//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Qualities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Qualities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clinica.Common.Resources.Qualities.ro-Ro", typeof(Qualities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehnologii avansate.
        /// </summary>
        internal static string advance_technology {
            get {
                return ResourceManager.GetString("advance_technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoluționarea clinicilor cu tehnologie avansată pentru rezultate optime în îngrijirea pacientului..
        /// </summary>
        internal static string advance_technology_description {
            get {
                return ResourceManager.GetString("advance_technology_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc confortabil.
        /// </summary>
        internal static string comfortable_place {
            get {
                return ResourceManager.GetString("comfortable_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crearea unui mediu primitor pentru ca pacienții să se simtă confortabil și relaxați..
        /// </summary>
        internal static string comfortable_place_description {
            get {
                return ResourceManager.GetString("comfortable_place_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angajati prietenosi.
        /// </summary>
        internal static string friendly_staff {
            get {
                return ResourceManager.GetString("friendly_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asigurarea unei atmosfere calde cu personal prietenos și util în clinici..
        /// </summary>
        internal static string friendly_staff_description {
            get {
                return ResourceManager.GetString("friendly_staff_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echipamente de calitate.
        /// </summary>
        internal static string quality_equipment {
            get {
                return ResourceManager.GetString("quality_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echiparea clinicilor cu tehnologie de vârf pentru diagnostic și tratament superior..
        /// </summary>
        internal static string quality_equipment_description {
            get {
                return ResourceManager.GetString("quality_equipment_description", resourceCulture);
            }
        }
    }
}
